config/routes.rb
Latted::Application.routes.draw do

  resources :comments
  resources :attachments
  resources :item_categories
  resources :item_catalogs


  devise_for :users
  root :to => "home#index"

  get "home/index"

  resources :items
  resources :users


  get 'items/:id/action/:act' => 'items#action', :as => "item_action"
  get 'items/:id/who/:act' => 'items#who_actioned', :as => "item_who_actioned"
  get 'users/:id/latte' => 'users#follow', :as => "follow_user"
  get 'users/:id/delatte' => 'users#unfollow', :as => "unfollow_user"
end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
  attr_accessible :title

  has_many :items
end

app/controllers/item_categories_controller.rb
class ItemCategoriesController < ApplicationController
  # GET /item_categories
  # GET /item_categories.json
  def index
    @item_categories = ItemCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @item_categories }
    end
  end

  # GET /item_categories/1
  # GET /item_categories/1.json
  def show
    @item_category = ItemCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item_category }
    end
  end

  # GET /item_categories/new
  # GET /item_categories/new.json
  def new
    @item_category = ItemCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item_category }
    end
  end

  # GET /item_categories/1/edit
  def edit
    @item_category = ItemCategory.find(params[:id])
  end

  # POST /item_categories
  # POST /item_categories.json
  def create
    @item_category = ItemCategory.new(params[:item_category])

    respond_to do |format|
      if @item_category.save
        format.html { redirect_to @item_category, notice: 'Item category was successfully created.' }
        format.json { render json: @item_category, status: :created, location: @item_category }
      else
        format.html { render action: "new" }
        format.json { render json: @item_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /item_categories/1
  # PUT /item_categories/1.json
  def update
    @item_category = ItemCategory.find(params[:id])

    respond_to do |format|
      if @item_category.update_attributes(params[:item_category])
        format.html { redirect_to @item_category, notice: 'Item category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_categories/1
  # DELETE /item_categories/1.json
  def destroy
    @item_category = ItemCategory.find(params[:id])
    @item_category.destroy

    respond_to do |format|
      format.html { redirect_to item_categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/item_categories_helper.rb
module ItemCategoriesHelper
end

app/views/item_categories/_form.html.erb
<%= form_for(@item_category) do |f| %>
  <% if @item_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_category.errors.count, "error") %> prohibited this item_category from being saved:</h2>

      <ul>
      <% @item_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_categories/edit.html.erb
<h1>Editing item_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_category %> |
<%= link_to 'Back', item_categories_path %>

app/views/item_categories/index.html.erb
<h1>Listing item_categories</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @item_categories.each do |item_category| %>
  <tr>
    <td><%= item_category.title %></td>
    <td><%= link_to 'Show', item_category %></td>
    <td><%= link_to 'Edit', edit_item_category_path(item_category) %></td>
    <td><%= link_to 'Destroy', item_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item category', new_item_category_path %>

app/views/item_categories/new.html.erb
<h1>New item_category</h1>

<%= render 'form' %>

<%= link_to 'Back', item_categories_path %>

app/views/item_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @item_category.title %>
</p>


<%= link_to 'Edit', edit_item_category_path(@item_category) %> |
<%= link_to 'Back', item_categories_path %>