config/routes.rb
Latted::Application.routes.draw do

  resources :comments
  resources :attachments
  resources :item_categories
  resources :item_catalogs


  devise_for :users
  root :to => "home#index"

  get "home/index"

  resources :items
  resources :users


  get 'items/:id/action/:act' => 'items#action', :as => "item_action"
  get 'items/:id/who/:act' => 'items#who_actioned', :as => "item_who_actioned"
  get 'users/:id/latte' => 'users#follow', :as => "follow_user"
  get 'users/:id/delatte' => 'users#unfollow', :as => "unfollow_user"
end

app/models/item_catalog.rb
class ItemCatalog < ActiveRecord::Base
  attr_accessible :title, :user_id
end

app/controllers/item_catalogs_controller.rb
class ItemCatalogsController < ApplicationController
  # GET /item_catalogs
  # GET /item_catalogs.json
  def index
    @item_catalogs = ItemCatalog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @item_catalogs }
    end
  end

  # GET /item_catalogs/1
  # GET /item_catalogs/1.json
  def show
    @item_catalog = ItemCatalog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item_catalog }
    end
  end

  # GET /item_catalogs/new
  # GET /item_catalogs/new.json
  def new
    @item_catalog = ItemCatalog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item_catalog }
    end
  end

  # GET /item_catalogs/1/edit
  def edit
    @item_catalog = ItemCatalog.find(params[:id])
  end

  # POST /item_catalogs
  # POST /item_catalogs.json
  def create
    @item_catalog = ItemCatalog.new(params[:item_catalog])

    respond_to do |format|
      if @item_catalog.save
        format.html { redirect_to @item_catalog, notice: 'Item catalog was successfully created.' }
        format.json { render json: @item_catalog, status: :created, location: @item_catalog }
      else
        format.html { render action: "new" }
        format.json { render json: @item_catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /item_catalogs/1
  # PUT /item_catalogs/1.json
  def update
    @item_catalog = ItemCatalog.find(params[:id])

    respond_to do |format|
      if @item_catalog.update_attributes(params[:item_catalog])
        format.html { redirect_to @item_catalog, notice: 'Item catalog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item_catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_catalogs/1
  # DELETE /item_catalogs/1.json
  def destroy
    @item_catalog = ItemCatalog.find(params[:id])
    @item_catalog.destroy

    respond_to do |format|
      format.html { redirect_to item_catalogs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/item_catalogs_helper.rb
module ItemCatalogsHelper
end

app/views/item_catalogs/_form.html.erb
<%= form_for(@item_catalog) do |f| %>
  <% if @item_catalog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_catalog.errors.count, "error") %> prohibited this item_catalog from being saved:</h2>

      <ul>
      <% @item_catalog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_catalogs/edit.html.erb
<h1>Editing item_catalog</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_catalog %> |
<%= link_to 'Back', item_catalogs_path %>

app/views/item_catalogs/index.html.erb
<h1>Listing item_catalogs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @item_catalogs.each do |item_catalog| %>
  <tr>
    <td><%= item_catalog.title %></td>
    <td><%= item_catalog.user_id %></td>
    <td><%= link_to 'Show', item_catalog %></td>
    <td><%= link_to 'Edit', edit_item_catalog_path(item_catalog) %></td>
    <td><%= link_to 'Destroy', item_catalog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item catalog', new_item_catalog_path %>

app/views/item_catalogs/new.html.erb
<h1>New item_catalog</h1>

<%= render 'form' %>

<%= link_to 'Back', item_catalogs_path %>

app/views/item_catalogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @item_catalog.title %>
</p>

<p>
  <b>User:</b>
  <%= @item_catalog.user_id %>
</p>


<%= link_to 'Edit', edit_item_catalog_path(@item_catalog) %> |
<%= link_to 'Back', item_catalogs_path %>