config/routes.rb
Latted::Application.routes.draw do

  resources :comments
  resources :attachments
  resources :item_categories
  resources :item_catalogs


  devise_for :users
  root :to => "home#index"

  get "home/index"

  resources :items
  resources :users


  get 'items/:id/action/:act' => 'items#action', :as => "item_action"
  get 'items/:id/who/:act' => 'items#who_actioned', :as => "item_who_actioned"
  get 'users/:id/latte' => 'users#follow', :as => "follow_user"
  get 'users/:id/delatte' => 'users#unfollow', :as => "unfollow_user"
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :default_values
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :login
  # attr_accessible :title, :body

  ## FOLLOWING AND FOLLOWERS
  has_many :items
  has_many :comments

  has_many :followings, :foreign_key => "follower_id",
           :dependent => :destroy
  has_many :followed_users, :through => :followings, :source => :followed

  has_many :reverse_relationships, :foreign_key => "followed_id",
           :class_name => "Following",
           :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower

  ## LIKES
  has_many :user_actions
  has_many :actions, :through => :user_actions, :source => :item



  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def following?(followed)
    followings.find_by_followed_id(followed)
  end

  def follow!(followed_id)
    followings.create!(:followed_id => followed_id)
  end

  def unfollow!(followed)
    followings.find_by_followed_id(followed).destroy
  end


  def method_missing(method_id, *arguments)
    if match = /([_a-zA-Z]\w*)_it/.match(method_id.to_s)
      action_name = match[1]
      action_type = UserActionType.find_by_name(action_name)
      action = action_type.user_actions.new
      action.user = self
      action.item = arguments[0]
      action_type.save
      action.save
      self.increment(action_name + "s")
      self.save
    elsif match = /my_([_a-zA-Z]\w*)s/.match(method_id.to_s)
      action_name = match[1]

      user_actions.joins('LEFT JOIN user_action_types ON user_action_types.id = user_actions.user_action_type_id').where('user_action_types.name = "'+ action_name +'"').collect{|a| a.item }
    else
      super
    end
  end


  def default_values
    self.wants ||= 0
    self.likes ||= 0
    self.owns ||= 0
    self.followers ||= 0
    self.follows ||= 0
  end

  def display_name
    self.username
  end
end

app/models/user_action.rb
class UserAction < ActiveRecord::Base
  attr_accessible :item_id, :user_action_type_id, :user_id
  validates_uniqueness_of :item_id, :scope => [:user_action_type_id, :user_id]

  belongs_to :user
  belongs_to :item
  belongs_to :user_action_type

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout :resolve_layout

  def show
    @user = User.find(params[:id])
    @me = current_user.nil? ? false : (current_user.id == @user.id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  def follow
    current_user.follow!(params["id"]);
    respond_to do |format|
      format.js
    end
    end

  def unfollow
    current_user.unfollow!(params["id"]);
    respond_to do |format|
      format.js
    end
  end

  private

  def render(*args)
    options = args.extract_options!
    options[:template] = "/users/#{params[:action]}"
    super(*(args << options))
  end

  private

  def resolve_layout
    case action_name
      when "show"
        "wide_layout"
      else
        "application"
    end
  end
end

app/views/users/_item.erb
<li class="span3 clearfix user-item" id="i-<%=item.id%>">
  <div class="thumbImage">
    <a href="#"><img src="<%=item.thumb_url(:small)%>" alt=""></a>
  </div>
  <div class="thumbSetting">
    <div class="thumbTitle">
      <a href="<%=item_url(item)%>" class="invarseColor">
        <%=item.title%>
      </a>
      <br>
      <small><%=item.created_at%></small>
    </div>
  </div>
  <div class="item-more" >
    Likes: <%=item.who_likes.count%>
    Wants: <%=item.who_wants.count%>
    Owns: <%=item.who_owns.count%>
  </div>
</li>

app/views/users/_sidebar.html.erb
<aside class="span3">

  <div class="categories">
    <div class="titleHeader clearfix">
      <h3><%=@user.username%></h3>
    </div><!--end titleHeader-->
    <div class="blog-adds no-top-margin">
      <a href="#"><img src="http://placehold.it/214x200" alt="Adds"></a>
    </div>

    <% if !@me && !current_user.nil? %>
        <% if current_user.following?(@user).nil? %>
            <div class="user-follow">
              <%= link_to (t "Follow"), follow_user_path(@user.id), :remote => true, :class => "btn btn-primary btn-small btn-block follow-button"%>
              <%= link_to (t "Unfollow"), unfollow_user_path(@user.id), :remote => true, :class => "btn btn-primary btn-small btn-block unfollow-button", :style=> "display:none"%>
            </div>
        <% else %>
            <div class="user-follow">
              <%= link_to (t "Follow"), follow_user_path(@user.id), :remote => true, :class => "btn btn-primary btn-small btn-block follow-button hide"%>
              <%= link_to (t "Unfollow"), unfollow_user_path(@user.id), :remote => true, :class => "btn btn-primary btn-small btn-block unfollow-button"%>
            </div>
        <% end %>
    <% end %>

    <ul class="unstyled tabs">
      <li><a class="invarseColor" href="#" data-tab="followers"><i class="icon-eye-open"></i>Followers (<%=@user.followers.count%>)</a></li>
      <li><a class="invarseColor" href="#" data-tab="following"><i class="icon-user"></i>Following (<%=@user.followed_users.count%>)</a></li>
    </ul>

    <ul class="unstyled tabs">
      <li><a class="invarseColor" href="#" data-tab="owns"><i class="icon-star"></i>Owns (<%=@user.owns%>)</a></li>
      <li><a class="invarseColor" href="#" data-tab="wants"><i class="icon-tags"></i>Wants (<%=@user.wants%>)</a></li>
      <li><a class="invarseColor" href="#" data-tab="likes"><i class="icon-heart"></i>Likes (<%=@user.likes%>)</a></li>
    </ul>

  </div><!--end categories-->


</aside><!--end aside-->

app/views/users/_user.html.erb
<li class="span2 clearfix user">
  <div class="user-thumb">
    <a href="<%=user_url(user.id)%>"><img src="/assets/img/72x72.jpg" alt="product image"></a>
  </div>
  <div class="user-username">
    <%=link_to user.username, user_path(user.id)%>
  </div>
</li>

app/views/users/follow.js.erb
$(".follow-button").hide();
$(".unfollow-button").css("display", "block");

app/views/users/show.html.erb
<section class="search-results">
<div class="container">
<div class="row">
<aside class="span3">
    <div class="widgets-container">

        <div class="widget user-profile-widget">
            <h4 class="title"><i class="icon-user icon-large"></i>&nbsp;<%= t 'User Profile' %></h4>
            <div class="user-profile-image">
                <a href="#"><img src="http://placehold.it/214x200" alt="Adds"></a>
            </div>
            <h5><%=@user.username%></h5>
        </div>

        <div class="widget">
          <% if !@me && !current_user.nil? %>
              <% if current_user.following?(@user).nil? %>
                  <div class="user-follow">
                    <%= link_to raw('<i class="icon-fire icon-large"></i>&nbsp;') + (t "Latte!"), follow_user_path(@user.id), :remote => true, :class => "btn btn-large follow-button"%>
                    <%= link_to raw('<i class="icon-coffee icon-large"></i>&nbsp;') + (t "Delatte!"), unfollow_user_path(@user.id), :remote => true, :class => "btn btn-large unfollow-button", :style=> "display:none"%>
                  </div>
              <% else %>
                  <div class="user-follow">
                    <%= link_to raw('<i class="icon-fire icon-large"></i>&nbsp;') + (t "Latte!"), follow_user_path(@user.id), :remote => true, :class => "btn btn-primary btn-small btn-block follow-button hide"%>
                    <%= link_to raw('<i class="icon-coffee icon-large"></i>&nbsp;') + (t "Delatte!"), unfollow_user_path(@user.id), :remote => true, :class => "btn btn-large unfollow-button"%>
                  </div>
              <% end %>
          <% end %>
        </div>
        <!-- end widget -->

        <div class="widget">
            <ul class="unstyled tabs">
              <li><a class="" href="#" data-tab="comments" data-title="<%= raw(t('User Comments')) %>"><i class="icon-star"></i><%= t 'Comments' %> </a></li>
              <li><a class="" href="#" data-tab="tags" data-title="<%=  h t 'User Tags' %>"><i class="icon-tags"></i><%= t 'Tags' %> </a></li>
            </ul>
        </div>
        <!-- end widget -->



    </div>
        <!-- end widgets-container -->
</aside>
<!-- end span3 -->


<!-- ITEMS -->
    <div class="search-result-title">
        <div class="span9">
          <div class="row-fluid">
            <div class="span8">
              <h4 class="title tab-title" ><%= "User Comments" %></h4>
            </div>
            <!-- end span8 -->
            <div class="span4">
              <div class="portfolio-controllers-container">
                <p class="pull-left sort-title"><%= "Sort by" %> -</p>

                <div class="btn-group">
                  <button class="btn btn-large">Downloads</button>
                  <button class="btn btn-large dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" id="filters">
                    <!-- dropdown menu links -->
                    <li><a href="#" data-filter="*" class="selected">Show All</a></li>
                    <li><a href="#" data-filter=".transition">Size</a></li>
                    <li><a href="#" data-filter=".metal">Price</a></li>
                    <li><a href="#" data-filter=".alkali">Date</a></li>
                  </ul>
                </div>
                <!-- end btn-group -->
              </div>
              <!-- end portfolio-controllers-container -->
            </div>
            <!-- end span4 -->

          </div>
          <!-- end row-fluid -->

          <section class="top-images v2">
            <div class="images-container v3">
              <div class="row">
                <div id="portfolio-container">


                  <div id="user-tabs">
                    <div class="row-fluid user-items comments" style="display: none" >
                         Comments
                    </div>
                    <div class="row-fluid user-items tags" >
                         Tags
                    </div>
                  </div>



                </div>
              </div>
            </div>
          </section>
        </div>
        <!-- end span9 -->
    </div>
    <!-- end search-result-title -->
<!-- END ITEMS -->

</div>
<!-- end row -->
</div> <!-- end container -->
</section> <!-- end search-results -->

app/views/users/unfollow.js.erb
$(".unfollow-button").hide();
$(".follow-button").css("display", "block");